version: '3.8'
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
  db:
    image: postgres:13.3-alpine
    container_name: stock-db
    restart: always
    command: postgres -c 'max_connections=100'
    volumes:
      - pq-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: dev
      TZ: Asia/Seoul
      # 이어서 시작할때 필요함. 기존데이터로 시작함.
      POSTGRES_CONFIG_hot_standby: "on"
    ports:
      - 5432:5432
    networks:
      - backend

  caddy:
    image: stock-caddy:latest
    restart: unless-stopped
    container_name: caddy
    volumes:
      - ./caddy/config/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/site:/srv
      - ./caddy/logs:/logs
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - 80:80
      - 443:443
      - 5000:5000
    networks:
      - frontend
      - backend
    command:  caddy run --config /etc/caddy/Caddyfile --watch

  stock-api:
    image: stock-read-pub-api:latest
    container_name: stock-api
    restart: always
    links:
      - db
    networks:
      - backend

  stock-write-ticker:
    image: stock-write-ticker:latest
    container_name: stock-write
    volumes:
      - log_stock_write_ticker:/logs-ticker
    links:
      - db
    networks:
      - backend

networks:
  frontend:
  backend:
volumes:
  caddy_data:
  caddy_config:
  pq-data:
  log_api:
  log_stock_write_ticker:
