# prometheus.yml
global:
  scrape_interval: 15s # default is 1 minute

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:9090']
